[package]
name = "openai-print"
version = "0.1.0"
authors = ["Sohaib Mahmood <smahmood@tutanota.com>"]
description = """
Standard printing of OpenAI response with a choice of JSON format
"""
keywords = ["openai", "chatgpt"]
edition = "2021"


[dependencies]
